-- Insertando Licenciaturas
INSERT INTO Licenciaturas (nombre_carrera, periodo, especialidad) VALUES
('Licenciatura en Informática', 8, 'Desarrollo de Software'),
('Licenciatura en Administración', 8, 'Recursos Humanos'),
('Licenciatura en Administración de Turistica', 8, 'Turismo'),
('Licenciatura en Psicología', 8, 'Psicología'),
('Licenciatura en Contaduría Pública', 9, 'Finanzas Públicas'),
('Licenciatura en Pedagogía', 8, 'Pedagogía'),
('Arquitectura', 10, 'Arquitectura'),
('Licenciatura en Derecho', 9, 'Derecho'),
('Licenciatura en Comunicación', 8, 'Producción Audiovisual'),
('Licenciatura Diseño Gráfico', 8, 'Diseño');

-- Insertando Maestros
INSERT INTO Maestro (nocontrol, apellidopat, apellidomat, nombre, fechanacimiento, telefono, correo, sexo) VALUES
('99999999', 'García', 'López', 'Juan Carlos', '1980-05-15', '5551234567', 'oaxcatjuanga@lameso.edu.mx', 'M'),
('87654321', 'Martínez', 'Gómez', 'Ana María', '1985-08-22', '5552345678', 'oaxcatanama@lameso.edu.mx', 'F'),
('87654329', 'Rodríguez', 'Hernández', 'Luis Alberto', '1975-11-10', '5553456789', 'oaxcatluisro@lameso.edu.mx', 'M'),
('87654319', 'Fernández', 'Pérez', 'María José', '1990-03-05', '5554567890', 'oaxcatmariafe@lameso.edu.mx', 'F'),
('87654318', 'López', 'García', 'José Luis', '1982-07-18', '5555678901', 'oaxcatjoselu@lameso.edu.mx', 'M'),
('87654317', 'González', 'Martínez', 'Laura Elena', '1978-09-25', '5556789012', 'oaxcatlaurael@lameso.edu.mx', 'F'),
('87654316', 'Pérez', 'Rodríguez', 'Carlos Alberto', '1988-12-30', '5557890123', 'oaxcatcarlospe@lameso.edu.mx', 'M'),
('87654315', 'Sánchez', 'Fernández', 'Patricia Guadalupe', '1983-02-14', '5558901234', 'oaxcatpatisa@lameso.edu.mx', 'F'),
('87654314', 'Ramírez', 'Sánchez', 'Miguel Ángel', '1979-06-20', '5559012345', 'oaxcatmiguelra@lameso.edu.mx', 'M'),
('87654313', 'Cruz', 'Ramírez', 'Martha Leticia', '1986-10-08', '5550123456', 'oaxcatmarthacr@lameso.edu.mx', 'F');

-- Insertando Materias


-- Insertando Materias
INSERT INTO Materias (materia, idlicenciaturas, semestre, grupo, turno, clave) VALUES
('Administración I', 2, 1, '1', 'Matutino', 'ADMIILA'),
('Contabilidad I', 2, 1, '1', 'Matutino', 'CONTILA'),
('Nociones de Derecho', 2, 1, '1', 'Matutino', 'NOCIDERELA'),
('Introducción a la Economía', 2, 1, '1', 'Matutino', 'INTRECONLA'),
('Matemáticas I', 2, 1, '1', 'Matutino', 'MATEILA'),
('Técnicas de Investigación', 2, 1, '1', 'Matutino', 'TECNINVELA'),
('Administración II', 2, 2, '1', 'Matutino', 'ADMIIILA'),
('Contabilidad II', 2, 2, '1', 'Matutino', 'CONTIILA'),
('Matemáticas II', 2, 2, '1', 'Matutino', 'MATEIILA'),
('Derecho Civil', 2, 2, '1', 'Matutino', 'DERECIVILA'),
('Microeconomía', 2, 2, '1', 'Matutino', 'MICRLA'),
('Sociología de la Empresa', 2, 2, '1', 'Matutino', 'SOCIEMPRLA'),
('Contabilidad Financiera', 2, 2, '1', 'Matutino', 'CONTFINALA'),
('Administración III', 2, 3, '1', 'Matutino', 'ADMIIIILA'),
('Contabilidad III', 2, 3, '1', 'Matutino', 'CONTIIILA'),
('Matemáticas Financieras', 2, 3, '1', 'Matutino', 'MATEFINALA'),
('Derecho Mercantil', 2, 3, '1', 'Matutino', 'DEREMERCLA'),
('Macroeconomía', 2, 3, '1', 'Matutino', 'MACRLA'),
('Herramientas Informáticas', 2, 3, '1', 'Matutino', 'HERRINFOLA'),
('Administración IV', 2, 4, '1', 'Matutino', 'ADMIIVLA'),
('Paquetes Computacionales', 2, 4, '1', 'Matutino', 'PAQUCOMPLA'),
('Costos', 2, 4, '1', 'Matutino', 'COSTLA'),
('Estadística', 2, 4, '1', 'Matutino', 'ESTALA'),
('Derecho del Trabajo', 2, 4, '1', 'Matutino', 'DERETRABLA'),
('Psicología Industrial', 2, 4, '1', 'Matutino', 'PSICINDULA'),
('Metodologías de Información', 2, 5, '1', 'Vespertino', 'METOINFOLA'),
('Fundamentos Financieros', 2, 5, '1', 'Vespertino', 'FUNDFINALA'),
('Administración y aplicación de costos', 2, 5, '1', 'Vespertino', 'ADMIAPLILA'),
('Derecho Fiscal', 2, 5, '1', 'Vespertino', 'DEREFISCLA'),
('Capital Humanos I', 2, 5, '1', 'Vespertino', 'CAPIHUMAILA'),
('Contabilidad de Sociedades', 2, 5, '1', 'Vespertino', 'CONTSOCILA'),
('Marco Empresarial', 2, 5, '1', 'Vespertino', 'MARCEMPRLA'),
('Finanzas Corporativas', 2, 6, '1', 'Vespertino', 'FINACORPLA'),
('Capital Humano II', 2, 6, '1', 'Vespertino', 'CAPIHUMAIILA'),
('Contabilidad administrativa I', 2, 6, '1', 'Vespertino', 'CONTADMIILA'),
('Mercadotecnia I', 2, 6, '1', 'Vespertino', 'MERCILA'),
('Obligaciones Fiscales', 2, 6, '1', 'Vespertino', 'OBLIFISCLA'),
('Sistemas de seguridad social', 2, 6, '1', 'Vespertino', 'SISTSEGULA'),
('Selección e integración del personal', 2, 6, '1', 'Vespertino', 'SELEINTELA'),
('Remuneración del trabajo I', 2, 6, '1', 'Vespertino', 'REMUTRABILA'),
('Análisis de la conducta del consumidor', 2, 6, '1', 'Vespertino', 'ANALCONSLA'),
('Investigación de Mercados', 2, 6, '1', 'Vespertino', 'INVEMERCLA'),
('Dirección', 2, 6, '1', 'Vespertino', 'DIRELA'),
('Desarrollo Empresarial', 2, 6, '1', 'Vespertino', 'DESAEMPRLA'),
('Contabilidad Administrativa II', 2, 7, '1', 'Vespertino', 'CONTADMIIILA'),
('Presupuestos', 2, 7, '1', 'Vespertino', 'PRESLA'),
('Comercio Internacional', 2, 7, '1', 'Vespertino', 'COMEINTELA'),
('Simulación de Negocios', 2, 7, '1', 'Vespertino', 'SIMUNEGOLA'),
('Mercadotecnia II', 2, 7, '1', 'Vespertino', 'MERCIILA'),
('Instrumentos de Financiamiento e Inversión', 2, 7, '1', 'Vespertino', 'INSTFINALA'),
('Administración de las Relaciones de Trabajo', 2, 7, '1', 'Vespertino', 'ADMIRELALA'),
('Remuneración del Trabajo II', 2, 7, '1', 'Vespertino', 'REMUTRABIILA'),
('Producto y Precio', 2, 7, '1', 'Vespertino', 'PRODPRECLA'),
('Ventas y Distribución', 2, 7, '1', 'Vespertino', 'VENTDISTLA'),
('Dirección Gerencial', 2, 7, '1', 'Vespertino', 'DIREGERELA'),
('Decisiones Gerenciales', 2, 7, '1', 'Vespertino', 'DECIGERELA'),
('Administración del Sector Público', 2, 8, '1', 'Vespertino', 'ADMIPUBLLA'),
('Auditoría Administrativa', 2, 8, '1', 'Vespertino', 'AUDIADMILA'),
('Comportamiento Organizacional', 2, 8, '1', 'Vespertino', 'COMPORGALA'),
('Seminario de Investigación', 2, 8, '1', 'Vespertino', 'SEMIINVELA'),
('Evaluación de Proyectos de Inversión', 2, 8, '1', 'Vespertino', 'EVALPROYLA'),
('Relaciones colectivas de trabajo', 2, 8, '1', 'Vespertino', 'RELACOLELA'),
('Auditoría de Personal', 2, 8, '1', 'Vespertino', 'AUDIPERSLA'),
('Marketing Contemporáneo y Nuevos Enfoques', 2, 8, '1', 'Vespertino', 'MARKCONTLA'),
('Mercados Especializados', 2, 8, '1', 'Vespertino', 'MERCESPELA'),
('Habilidades Directivas', 2, 8, '1', 'Vespertino', 'HABIDIRELA'),
('Dirección Estratégica', 2, 8, '1', 'Vespertino', 'DIREESTRLA'),
('Administración I', 3, 1, '1', 'Matutino', 'ADMIILAT'),
('Contabilidad I', 3, 1, '1', 'Matutino', 'CONTILAT'),
('Introducción a la Economía', 3, 1, '1', 'Matutino', 'INTRECONLAT'),
('Fundamentos del Derecho', 3, 1, '1', 'Matutino', 'FUNDDERELAT'),
('Técnicas de Investigación', 3, 1, '1', 'Matutino', 'TECNINVELAT'),
('Teoría del Turismo', 3, 1, '1', 'Matutino', 'TEORTURILAT'),
('Inglés I', 3, 1, '1', 'Matutino', 'INGLILAT'),
('Laboratorio de Alimentos y Bebidas I', 3, 1, '1', 'Matutino', 'LABOALIMILAT'),
('Administración II', 3, 2, '1', 'Matutino', 'ADMIIILAT'),
('Contabilidad II', 3, 2, '1', 'Matutino', 'CONTIILAT'),
('Matemáticas Financieras', 3, 2, '1', 'Matutino', 'MATEFINALAT'),
('Microeconomía', 3, 2, '1', 'Matutino', 'MICRLAT'),
('Psicología Industrial', 3, 2, '1', 'Matutino', 'PSICINDULAT'),
('Geografía y Patrimonio Turístico Nacional', 3, 2, '1', 'Matutino', 'GEOGPATRLAT'),
('Inglés II', 3, 2, '1', 'Matutino', 'INGLIILAT'),
('Laboratorio de Alimentos y Bebidas II', 3, 2, '1', 'Matutino', 'LABOALIMIILAT'),
('Administración III', 3, 3, '1', 'Matutino', 'ADMIIIILAT'),
('Macroeconomía', 3, 3, '1', 'Matutino', 'MACRLAT'),
('Geografía y Patrimonio Turístico Internacional', 3, 3, '1', 'Matutino', 'GEOGINTELAT'),
('Derecho Mercantil', 3, 3, '1', 'Matutino', 'DEREMERCLAT'),
('Sociología de la Empresa', 3, 3, '1', 'Matutino', 'SOCIEMPRLAT'),
('Herramientas Informáticas', 3, 3, '1', 'Matutino', 'HERRINFOLAT'),
('Inglés III', 3, 3, '1', 'Matutino', 'INGLIIILAT'),
('Laboratorio de Alimentos y Bebidas III', 3, 3, '1', 'Matutino', 'LABOALIMIIILAT'),
('Administración IV', 3, 4, '1', 'Matutino', 'ADMIIVLAT'),
('Estadística', 3, 4, '1', 'Matutino', 'ESTALAT'),
('Software Turístico', 3, 4, '1', 'Matutino', 'SOFTTURILAT'),
('Tecnología de Restaurantes y Bares', 3, 4, '1', 'Matutino', 'TECNRESTLAT'),
('Agencia de Viajes', 3, 4, '1', 'Matutino', 'AGENVIAJLAT'),
('Tecnología del Hospedaje', 3, 4, '1', 'Matutino', 'TECNHOSPLAT'),
('Inglés IV', 3, 4, '1', 'Matutino', 'INGLIVLAT'),
('Laboratorio de Alimentos y Bebidas IV', 3, 4, '1', 'Matutino', 'LABOALIMIVLAT'),
('Legislación Turística', 3, 5, '1', 'Vespertino', 'LEGITURILAT'),
('Costos de Empresas Turísticas', 3, 5, '1', 'Vespertino', 'COSTTURILAT'),
('Mercadotecnia', 3, 5, '1', 'Vespertino', 'MERCLAT'),
('Derecho del Trabajo', 3, 5, '1', 'Vespertino', 'DERETRABLAT'),
('Sistemas de Transportación', 3, 5, '1', 'Vespertino', 'SISTTRANLAT'),
('Desarrollo Organizacional', 3, 5, '1', 'Vespertino', 'DESAORGALAT'),
('Inglés V', 3, 5, '1', 'Vespertino', 'INGLVLAT'),
('Laboratorio de Alimentos y Bebidas V', 3, 5, '1', 'Vespertino', 'LABOALIMVLAT'),
('Mercadotecnia Turística', 3, 6, '1', 'Vespertino', 'MERCTURILAT'),
('Circuitos Turísticos Nacionales', 3, 6, '1', 'Vespertino', 'CIRCTURILAT'),
('Instalaciones y Mantenimiento de Hoteles y Restaurantes', 3, 6, '1', 'Vespertino', 'INSTMANTLAT'),
('Planeación del Desarrollo Turístico Sustentable I', 3, 6, '1', 'Vespertino', 'PLANSUSTILAT'),
('Alimentos y Nutrición', 3, 6, '1', 'Vespertino', 'ALIMNUTRLAT'),
('Enología y Quesos', 3, 6, '1', 'Vespertino', 'ENOLQUESLAT'),
('Laboratorio de Gastronomía I', 3, 6, '1', 'Vespertino', 'LABOGASTILAT'),
('Administración Hotelera', 3, 6, '1', 'Vespertino', 'ADMIHOTELAT'),
('Relaciones Públicas y Hospitalidad', 3, 6, '1', 'Vespertino', 'RELAHOSPLAT'),
('Inglés Turístico I', 3, 6, '1', 'Vespertino', 'INGLTURIILAT'),
('Capital Humano', 3, 7, '1', 'Vespertino', 'CAPIHUMALAT'),
('Organización de Grupos y Convenciones', 3, 7, '1', 'Vespertino', 'ORGACONVLAT'),
('Circuitos Turísticos Internacionales', 3, 7, '1', 'Vespertino', 'CIRCINTELAT'),
('Planeación del Desarrollo Turístico Sustentable II', 3, 7, '1', 'Vespertino', 'PLANSUSTIILAT'),
('Sistemas de Calidad y Certificación de Restaurantes', 3, 7, '1', 'Vespertino', 'SISTCERTLAT'),
('Confitería y Chocolatería', 3, 7, '1', 'Vespertino', 'CONFCHOCLAT'),
('Laboratorio de Gastronomía II', 3, 7, '1', 'Vespertino', 'LABOGASTIILAT'),
('Alta Dirección Hotelera', 3, 7, '1', 'Vespertino', 'ALTADIRELAT'),
('Finanzas Hoteleras', 3, 7, '1', 'Vespertino', 'FINAHOTELAT'),
('Inglés Turístico II', 3, 7, '1', 'Vespertino', 'INGLTURIIILAT'),
('Auditoría Turística', 3, 8, '1', 'Vespertino', 'AUDITURILAT'),
('Formulación de Proyectos de Inversión Turística', 3, 8, '1', 'Vespertino', 'FORMPROYLAT'),
('Dirección Estratégica y Habilidades Gerenciales', 3, 8, '1', 'Vespertino', 'DIREESTRLAT'),
('Seminario de Investigación', 3, 8, '1', 'Vespertino', 'SEMIINVELAT'),
('Dirección y Manejo de Alimentación Institucional', 3, 8, '1', 'Vespertino', 'DIREINSTLAT'),
('Panadería', 3, 8, '1', 'Vespertino', 'PANALAT'),
('Laboratorio de Gastronomía III', 3, 8, '1', 'Vespertino', 'LABOGASTIIILAT'),
('Diseño de Sistemas de Servicio Hotelero', 3, 8, '1', 'Vespertino', 'DISESISTLAT'),
('Sistemas de Calidad y Certificación Hotelera', 3, 8, '1', 'Vespertino', 'SISTCERTLAT2'),
('Inglés Turístico III', 3, 8, '1', 'Vespertino', 'INGLTURIIIILAT'),
('Historia de la Arquitectura I', 7, 1, '1', 'Matutino', 'HISTARQUIARQ'),
('Teoría del Diseño', 7, 1, '1', 'Matutino', 'TEORDISEARQ'),
('Dibujo Arquitectónico I', 7, 1, '1', 'Matutino', 'DIBUARQUIARQ'),
('Concepto Estructural', 7, 1, '1', 'Matutino', 'CONCESTRARQ'),
('Diseño Básico I', 7, 1, '1', 'Matutino', 'DISEBASIIARQ'),
('Geometría Descriptiva I', 7, 1, '1', 'Matutino', 'GEOMDESCIARQ'),
('Matemáticas para la Arquitectura', 7, 1, '1', 'Matutino', 'MATEARQUARQ'),
('Técnicas de Investigación', 7, 1, '1', 'Matutino', 'TECNINVEARQ'),
('Historia de la Arquitectura II', 7, 2, '1', 'Matutino', 'HISTARQUIIARQ'),
('Dibujo Arquitectónico II', 7, 2, '1', 'Matutino', 'DIBUARQUIIARQ'),
('Estática', 7, 2, '1', 'Matutino', 'ESTAARQ'),
('Diseño Básico II', 7, 2, '1', 'Matutino', 'DISEBASIIIARQ'),
('Diseño Arquitectónico I', 7, 2, '1', 'Matutino', 'DISEARQUIARQ'),
('Maquetas y Modelos', 7, 2, '1', 'Matutino', 'MAQUMODEARQ'),
('Construcción y Materiales I', 7, 2, '1', 'Matutino', 'CONSMATEIARQ'),
('Geometría Descriptiva II', 7, 2, '1', 'Matutino', 'GEOMDESCIIARQ'),
('Historia de la Arquitectura III', 7, 3, '1', 'Matutino', 'HISTARQUIIIARQ'),
('Dibujo por Computadora I', 7, 3, '1', 'Matutino', 'DIBUCOMPIARQ'),
('Resistencia de Materiales', 7, 3, '1', 'Matutino', 'RESIMATEARQ'),
('Diseño Básico III', 7, 3, '1', 'Matutino', 'DISEBASIIIIARQ'),
('Diseño Arquitectónico II', 7, 3, '1', 'Matutino', 'DISEARQUIIARQ'),
('Teorías Arquitectónicas', 7, 3, '1', 'Matutino', 'TEORARQUARQ'),
('Construcción y Materiales II', 7, 3, '1', 'Matutino', 'CONSMATEIIARQ'),
('Instalaciones I', 7, 3, '1', 'Matutino', 'INSTIARQ'),
('Historia de la Arquitectura Mexicana I', 7, 4, '1', 'Matutino', 'HISTARQUIARQ2'),
('Dibujo por Computadora II', 7, 4, '1', 'Matutino', 'DIBUCOMPIIARQ'),
('Estructuras de Concreto I', 7, 4, '1', 'Matutino', 'ESTRCONCIARQ'),
('Diseño Arquitectónico III', 7, 4, '1', 'Matutino', 'DISEARQUIIIARQ'),
('Metodología Proyectual', 7, 4, '1', 'Matutino', 'METOPROYARQ'),
('Geometría Aplicada', 7, 4, '1', 'Matutino', 'GEOMAPLIARQ'),
('Construcción y Materiales III', 7, 4, '1', 'Matutino', 'CONSMATEIIIARQ'),
('Instalaciones II', 7, 4, '1', 'Matutino', 'INSTIIARQ'),
('Historia de la Arquitectura Mexicana II', 7, 5, '1', 'Vespertino', 'HISTARQUIIARQ2'),
('Dibujo por Computadora III', 7, 5, '1', 'Vespertino', 'DIBUCOMPIIIARQ'),
('Diseño Arquitectónico IV', 7, 5, '1', 'Vespertino', 'DISEARQUIVARQ'),
('Estructuras de Concreto II', 7, 5, '1', 'Vespertino', 'ESTRCONCIIARQ'),
('Proyecto Constructivo', 7, 5, '1', 'Vespertino', 'PROYCONSARQ'),
('Sustentabilidad', 7, 5, '1', 'Vespertino', 'SUSTARQ'),
('Arquitectura Bioclimática', 7, 5, '1', 'Vespertino', 'ARQUBIOCARQ'),
('Mercadotecnia', 7, 5, '1', 'Vespertino', 'MERCARQ'),
('Urbanismo', 7, 6, '1', 'Vespertino', 'URBAARQ'),
('Estructuras de Madera y Acero', 7, 6, '1', 'Vespertino', 'ESTRMADEARQ'),
('Diseño Arquitectónico V', 7, 6, '1', 'Vespertino', 'DISEARQUVARQ'),
('Visualización Digital', 7, 6, '1', 'Vespertino', 'VISUDIGIARQ'),
('Costos', 7, 6, '1', 'Vespertino', 'COSTARQ'),
('Color en la Arquitectura', 7, 6, '1', 'Vespertino', 'COLOARQUARQ'),
('Jardinería y Paisajismo I', 7, 6, '1', 'Vespertino', 'JARDPAISIARQ'),
('Iluminación y Acústica', 7, 6, '1', 'Vespertino', 'ILUMACUSARQ'),
('Administración', 7, 6, '1', 'Vespertino', 'ADMIARQ'),
('Sociedad, Economía y Política de México', 7, 6, '1', 'Vespertino', 'SOCIECONARQ'),
('Instalaciones Especiales', 7, 6, '1', 'Vespertino', 'INSTESPEARQ'),
('Análisis Urbano', 7, 7, '1', 'Vespertino', 'ANALURBAARQ'),
('Seminario de Restauración', 7, 7, '1', 'Vespertino', 'SEMIRESTARQ'),
('Contratación de Obras', 7, 7, '1', 'Vespertino', 'CONTOBRAARQ'),
('Diseño Arquitectónico VI', 7, 7, '1', 'Vespertino', 'DISEARQUVIARQ'),
('Presupuestos', 7, 7, '1', 'Vespertino', 'PRESARQ'),
('Semiótica', 7, 7, '1', 'Vespertino', 'SEMIARQ'),
('Jardinería y Paisajismo II', 7, 7, '1', 'Vespertino', 'JARDPAISIIARQ'),
('Arquitectura Contemporánea', 7, 7, '1', 'Vespertino', 'ARQUCONTARQ'),
('Tecnología y Prefabricación en la Construcción', 7, 7, '1', 'Vespertino', 'TECNPREFARQ'),
('Administración de la Construcción', 7, 7, '1', 'Vespertino', 'ADMICONSARQ'),
('Antecedentes de Proyectos de Inversión', 7, 7, '1', 'Vespertino', 'ANTEPROYARQ'),
('Seminario de Investigación', 7, 8, '1', 'Vespertino', 'SEMIINVEARQ'),
('Proyecto Integrador', 7, 8, '1', 'Vespertino', 'PROYINTEARQ'),
('Ética Profesional', 7, 8, '1', 'Vespertino', 'ETICPROFARQ'),
('Diseño Arquitectónico VII', 7, 8, '1', 'Vespertino', 'DISEARQUVIIARQ'),
('Detalles Constructivos', 7, 8, '1', 'Vespertino', 'DETACONSARQ'),
('Integración Urbana', 7, 8, '1', 'Vespertino', 'INTEURBAARQ'),
('Tectónica', 7, 8, '1', 'Vespertino', 'TECTARQ'),
('Sistemas Alternos de Eficiencia Energética', 7, 8, '1', 'Vespertino', 'SISTEFICARQ'),
('Presupuestos II', 7, 8, '1', 'Vespertino', 'PRESIIARQ'),
('Proyectos de Inversión', 7, 8, '1', 'Vespertino', 'PROYINVEARQ'),
('Fundamentos de la Comunicación', 9, 1, '1', 'Matutino', 'FUNDCOMULC'),
('Técnicas de Investigación', 9, 1, '1', 'Matutino', 'TECNINVELC'),
('Taller de Expresión Escrita y Oral', 9, 1, '1', 'Matutino', 'TALLEXPRLC'),
('Discurso Literario I', 9, 1, '1', 'Matutino', 'DISCLITEILC'),
('Introducción a la Sociología', 9, 1, '1', 'Matutino', 'INTRSOCILC'),
('Psicología de la Personalidad', 9, 1, '1', 'Matutino', 'PSICPERSLC'),
('Historia y Teoría de los Medios', 9, 1, '1', 'Matutino', 'HISTTEORLC'),
('Teoría de la Comunicación I', 9, 2, '1', 'Matutino', 'TEORCOMUILC'),
('Diseño Gráfico', 9, 2, '1', 'Matutino', 'DISEGRAFLC'),
('Estadística', 9, 2, '1', 'Matutino', 'ESTALC'),
('Discurso Literario II', 9, 2, '1', 'Matutino', 'DISCLITEIILC'),
('Teoría Sociológica', 9, 2, '1', 'Matutino', 'TEORSOCILC'),
('Psicología Social', 9, 2, '1', 'Matutino', 'PSICSOCILC'),
('Filosofía Social', 9, 2, '1', 'Matutino', 'FILOSOCILC'),
('Teoría de la Comunicación II', 9, 3, '1', 'Matutino', 'TEORCOMUIILC'),
('Fotografía', 9, 3, '1', 'Matutino', 'FOTOLC'),
('Metodología Cuantitativa de Investigación en Comunicación', 9, 3, '1', 'Matutino', 'METOINVELC'),
('Discurso Literario III', 9, 3, '1', 'Matutino', 'DISCLITEIIILC'),
('Sociología de la Comunicación', 9, 3, '1', 'Matutino', 'SOCICOMULC'),
('Psicología de la Comunicación', 9, 3, '1', 'Matutino', 'PSICCOMULC'),
('Lingüística', 9, 3, '1', 'Matutino', 'LINGLC'),
('Teoría de la Comunicación III', 9, 4, '1', 'Matutino', 'TEORCOMUIIILC'),
('Semiótica', 9, 4, '1', 'Matutino', 'SEMILC'),
('Teoría del Conocimiento', 9, 4, '1', 'Matutino', 'TEORCONOLC'),
('Metodología Cualitativa de Investigación en Comunicación', 9, 4, '1', 'Matutino', 'METOINVELC2'),
('Apreciación Cinematográfica', 9, 4, '1', 'Matutino', 'APRECINELC'),
('Persuasión', 9, 4, '1', 'Matutino', 'PERSLC'),
('Guionismo para Medios Audiovisuales', 9, 4, '1', 'Matutino', 'GUIOAUDILC'),
('Fundamentos de Mercadotecnia', 9, 5, '1', 'Vespertino', 'FUNDMERCLC'),
('Publicidad', 9, 5, '1', 'Vespertino', 'PUBLLC'),
('Comunicación Organizacional I', 9, 5, '1', 'Vespertino', 'COMUORGAILC'),
('Apreciación y Crítica Teatral', 9, 5, '1', 'Vespertino', 'APRECRITLC'),
('Producción Televisiva y Medios Digitales', 9, 5, '1', 'Vespertino', 'PRODTELELC'),
('Producción Radiofónica y Plataformas Digitales', 9, 5, '1', 'Vespertino', 'PRODRADILC'),
('Periodismo', 9, 5, '1', 'Vespertino', 'PERILC'),
('Mercadotecnia Aplicada', 9, 6, '1', 'Vespertino', 'MERCAPLILC'),
('Comunicación Publicitaria', 9, 6, '1', 'Vespertino', 'COMUPUBLLC'),
('Comunicación Organizacional II', 9, 6, '1', 'Vespertino', 'COMUORGAIILC'),
('Taller de Periodismo', 9, 6, '1', 'Vespertino', 'TALLPERILC'),
('Comunicación Estratégica y Manejo de Crisis', 9, 6, '1', 'Vespertino', 'COMUESTRLC'),
('Desarrollo Organizacional', 9, 6, '1', 'Vespertino', 'DESAORGALC'),
('Dirección de Arte en Medios', 9, 6, '1', 'Vespertino', 'DIREMEDILC'),
('Postproducción Digital', 9, 6, '1', 'Vespertino', 'POSTDIGILC'),
('Creatividad Publicitaria y Construcción de Marcas', 9, 6, '1', 'Vespertino', 'CREAPUBLLC'),
('Dirección y Gestión Estratégica de la Comunicación', 9, 6, '1', 'Vespertino', 'DIRECOMULC'),
('Comunicación Política', 9, 7, '1', 'Vespertino', 'COMUPOLILC'),
('Derecho de Acceso a la Información', 9, 7, '1', 'Vespertino', 'DEREINFOLC'),
('Tecnologías de la Información y Comunicación', 9, 7, '1', 'Vespertino', 'TECNCOMULC'),
('Diseño y Producción Editorial', 9, 7, '1', 'Vespertino', 'DISEPRODLC'),
('Comunicación Institucional', 9, 7, '1', 'Vespertino', 'COMUINSTLC'),
('Taller de Comunicación Organizacional', 9, 7, '1', 'Vespertino', 'TALLORGALC'),
('Técnicas de Diseño Sonoro', 9, 7, '1', 'Vespertino', 'TECNDISELC'),
('Laboratorio de Realización Audiovisual', 9, 7, '1', 'Vespertino', 'LABOREALLC'),
('Producción Publicitaria', 9, 7, '1', 'Vespertino', 'PRODPUBLLC'),
('Propaganda y Mercadotecnia Política', 9, 7, '1', 'Vespertino', 'PROPMERCLC'),
('Opinión Pública', 9, 8, '1', 'Vespertino', 'OPINPUBLLC'),
('Seminario de Investigación', 9, 8, '1', 'Vespertino', 'SEMIINVELC'),
('Ética de la Comunicación y Valores Profesionales', 9, 8, '1', 'Vespertino', 'ETICPROFLC'),
('Comunicación para el Desarrollo Social', 9, 8, '1', 'Vespertino', 'COMUDESALC'),
('Diagnóstico Organizacional', 9, 8, '1', 'Vespertino', 'DIAGORGALC'),
('Seminario de Comunicación Organizacional', 9, 8, '1', 'Vespertino', 'SEMIORGALC'),
('Organización y Dirección de Medios Masivos', 9, 8, '1', 'Vespertino', 'ORGADIRELC'),
('Seminario de Producción en Medios Masivos', 9, 8, '1', 'Vespertino', 'SEMIPRODLC'),
('Desarrollo de Campañas Publicitarias', 9, 8, '1', 'Vespertino', 'DESAPUBLLC'),
('Marketing Contemporáneo y Nuevos Enfoques', 9, 8, '1', 'Vespertino', 'MARKCONTLC'),
('Administración I', 5, 1, '1', 'Matutino', 'ADMIILCP'),
('Contabilidad I', 5, 1, '1', 'Matutino', 'CONTILCP'),
('Nociones de Derecho', 5, 1, '1', 'Matutino', 'NOCIDERELCP'),
('Introducción a la Economía', 5, 1, '1', 'Matutino', 'INTRECONLCP'),
('Matemáticas I', 5, 1, '1', 'Matutino', 'MATEILCP'),
('Técnicas de Investigación', 5, 1, '1', 'Matutino', 'TECNINVELCP'),
('Administración II', 5, 2, '1', 'Matutino', 'ADMIIILCP'),
('Contabilidad II', 5, 2, '1', 'Matutino', 'CONTIILCP'),
('Matemáticas II', 5, 2, '1', 'Matutino', 'MATEIILCP'),
('Derecho Civil', 5, 2, '1', 'Matutino', 'DERECIVILCP'),
('Microeconomía', 5, 2, '1', 'Matutino', 'MICRLCP'),
('Sociología de la Empresa', 5, 2, '1', 'Matutino', 'SOCIEMPRLCP'),
('Introducción a la Informática', 5, 2, '1', 'Matutino', 'INTRINFOLCP'),
('Administración III', 5, 3, '1', 'Matutino', 'ADMIIIILCP'),
('Contabilidad III', 5, 3, '1', 'Matutino', 'CONTIIILCP'),
('Matemáticas Financieras', 5, 3, '1', 'Matutino', 'MATEFINALCP'),
('Derecho Mercantil', 5, 3, '1', 'Matutino', 'DEREMERCLCP'),
('Macroeconomía', 5, 3, '1', 'Matutino', 'MACRLCP'),
('Herramientas Informática', 5, 3, '1', 'Matutino', 'HERRINFOLCP'),
('Administración IV', 5, 4, '1', 'Matutino', 'ADMIIVLCP'),
('Paquetes Computacionales', 5, 4, '1', 'Matutino', 'PAQUCOMPLCP'),
('Costos', 5, 4, '1', 'Matutino', 'COSTLCP'),
('Estadística', 5, 4, '1', 'Matutino', 'ESTALCP'),
('Derecho del Trabajo', 5, 4, '1', 'Matutino', 'DERETRABLCP'),
('Psicología Industrial', 5, 4, '1', 'Matutino', 'PSICINDULCP'),
('Metodologías de información', 5, 5, '1', 'Vespertino', 'METOINFOLCP'),
('Fundamentos financieros', 5, 5, '1', 'Vespertino', 'FUNDFINALCP'),
('Administración y apliación de costos', 5, 5, '1', 'Vespertino', 'ADMIAPLILCP'),
('Teoría general impositiva', 5, 5, '1', 'Vespertino', 'TEORIMPOLCP'),
('Capital humano', 5, 5, '1', 'Vespertino', 'CAPIHUMALCP'),
('Contabilidad de Sociedades', 5, 5, '1', 'Vespertino', 'CONTSOCILCP'),
('Marco Empresarial', 5, 5, '1', 'Vespertino', 'MARCEMPRLCP'),
('Finanzas corporativas', 5, 6, '1', 'Vespertino', 'FINACORPLCP'),
('Auditoría I', 5, 6, '1', 'Vespertino', 'AUDIILCP'),
('Contabilidad Administrativa I', 5, 6, '1', 'Vespertino', 'CONTADMIILCP'),
('Teoría General Impositiva II', 5, 6, '1', 'Vespertino', 'TEORIMPOIILCP'),
('Economía y finanzas', 5, 6, '1', 'Vespertino', 'ECONFINALCP'),
('Impuestos I', 5, 6, '1', 'Vespertino', 'IMPUILCP'),
('Presupuestos', 5, 6, '1', 'Vespertino', 'PRESLCP'),
('Análisis de Estados Financieros', 5, 6, '1', 'Vespertino', 'ANALFINALCP'),
('Finanzas Públicas', 5, 6, '1', 'Vespertino', 'FINAPUBLLCP'),
('Contabilidad Administrativa II', 5, 7, '1', 'Vespertino', 'CONTADMIIILCP'),
('Auditoría II', 5, 7, '1', 'Vespertino', 'AUDIIILCP'),
('Comercio Internacional', 5, 7, '1', 'Vespertino', 'COMEINTELCP'),
('Simulación de Negocios', 5, 7, '1', 'Vespertino', 'SIMUNEGOLCP'),
('Obligaciones Fiscales', 5, 7, '1', 'Vespertino', 'OBLIFISCLCP'),
('Impuestos al Comercio Exterior', 5, 7, '1', 'Vespertino', 'IMPUCOMELCP'),
('Impuestos Indirectos', 5, 7, '1', 'Vespertino', 'IMPUINDILCP'),
('Impuestos II', 5, 7, '1', 'Vespertino', 'IMPUIILCP'),
('Mercados e Instrumentos Financieros', 5, 7, '1', 'Vespertino', 'MERCINSTLCP'),
('Instrumentos de Financiamiento e Inversión', 5, 7, '1', 'Vespertino', 'INSTFINALCP'),
('Tratamiento Contable y Fiscal de la Información Financiera', 5, 7, '1', 'Vespertino', 'TRATINFOLCP'),
('Auditoría Administrativa', 5, 8, '1', 'Vespertino', 'AUDIADMILCP'),
('Auditoría III', 5, 8, '1', 'Vespertino', 'AUDIIIILCP'),
('Habilidades Directivas', 5, 8, '1', 'Vespertino', 'HABIDIRELCP'),
('Seminario de Investigación', 5, 8, '1', 'Vespertino', 'SEMIINVELCP'),
('Tratamiento Contable y Fiscal de la Información Financiera', 5, 8, '1', 'Vespertino', 'TRATINFOLCP2'),
('Seminario de Planeación Fiscal', 5, 8, '1', 'Vespertino', 'SEMIPLANLCP'),
('Impuestos III', 5, 8, '1', 'Vespertino', 'IMPUIIILCP'),
('Planeación Financiera, Estratégica e Innovación', 5, 8, '1', 'Vespertino', 'PLANFINALCP'),
('Formulación y Evaluación de Proyectos de Inversión', 5, 8, '1', 'Vespertino', 'FORMEVALLCP'),
('Finanzas Internacionales y Bursátiles', 5, 8, '1', 'Vespertino', 'FINAINTELCP'),
('Derecho Romano', 8, 1, '1', 'Matutino', 'DEREROMALD'),
('Fundamentos de Derecho I', 8, 1, '1', 'Matutino', 'FUNDDEREILD'),
('Sociología Jurídica', 8, 1, '1', 'Matutino', 'SOCIJURILD'),
('Derecho Civil I', 8, 1, '1', 'Matutino', 'DERECIVIILD'),
('Técnicas de Investigación', 8, 1, '1', 'Matutino', 'TECNINVELD'),
('Teoría Política', 8, 1, '1', 'Matutino', 'TEORPOLILD'),
('Expresión Jurídica', 8, 2, '1', 'Matutino', 'EXPRJURILD'),
('Fundamentos de Derecho II', 8, 2, '1', 'Matutino', 'FUNDDEREIILD'),
('Derecho Civil II', 8, 2, '1', 'Matutino', 'DERECIVIIILD'),
('Hermenéutica Jurídica', 8, 2, '1', 'Matutino', 'HERMJURILD'),
('Teoría general del estado', 8, 2, '1', 'Matutino', 'TEORGENELD'),
('Metodología Jurídica', 8, 2, '1', 'Matutino', 'METOJURILD'),
('Derecho Constitucional I', 8, 3, '1', 'Matutino', 'DERECONSILD'),
('Derecho Penal I', 8, 3, '1', 'Matutino', 'DEREPENAILD'),
('Derecho Civil III', 8, 3, '1', 'Matutino', 'DERECIVIIIILD'),
('Teoría General del Proceso', 8, 3, '1', 'Matutino', 'TEORGENELD2'),
('Derechos Humanos I', 8, 3, '1', 'Matutino', 'DEREHUMAILD'),
('Derecho Administrativo I', 8, 3, '1', 'Matutino', 'DEREADMIILD'),
('Derecho Constitucional II', 8, 4, '1', 'Matutino', 'DERECONSIILD'),
('Derecho Penal II', 8, 4, '1', 'Matutino', 'DEREPENAIILD'),
('Derecho Civil IV', 8, 4, '1', 'Matutino', 'DERECIVIIVLD'),
('Derecho Procesal Civil', 8, 4, '1', 'Matutino', 'DEREPROCLD'),
('Derecho Administrativo II', 8, 4, '1', 'Matutino', 'DEREADMIIILD'),
('Derechos Humanos II', 8, 4, '1', 'Matutino', 'DEREHUMAIILD'),
('Derecho Internacional Público', 8, 5, '1', 'Vespertino', 'DEREINTELD'),
('Criminología y criminalística', 8, 5, '1', 'Vespertino', 'CRIMCRIMLD'),
('Derecho Mercantil I', 8, 5, '1', 'Vespertino', 'DEREMERCILD'),
('Derecho General del Amparo I', 8, 5, '1', 'Vespertino', 'DEREGENEILD'),
('Derecho Municipal', 8, 5, '1', 'Vespertino', 'DEREMUNILD'),
('Clínica de Derechos Humanos', 8, 5, '1', 'Vespertino', 'CLINDERELD'),
('Derecho Internacional Privado', 8, 6, '1', 'Vespertino', 'DEREINTELD2'),
('Juicios Orales I', 8, 6, '1', 'Vespertino', 'JUICORALILD'),
('Derecho Mercantil II', 8, 6, '1', 'Vespertino', 'DEREMERCIILD'),
('Teoría General del Amparo II', 8, 6, '1', 'Vespertino', 'TEORGENEIILD'),
('Derecho del Trabajo I', 8, 6, '1', 'Vespertino', 'DERETRABILD'),
('Derecho Agrario', 8, 6, '1', 'Vespertino', 'DEREAGRALD'),
('Derecho Fiscal I', 8, 7, '1', 'Vespertino', 'DEREFISCILD'),
('Juicios Orales II', 8, 7, '1', 'Vespertino', 'JUICORALIILD'),
('Contratos Mercantiles', 8, 7, '1', 'Vespertino', 'CONTMERCLD'),
('Práctica del Derecho del Amparo', 8, 7, '1', 'Vespertino', 'PRACDERELD'),
('Derecho del Trabajo II', 8, 7, '1', 'Vespertino', 'DERETRABIILD'),
('Derecho Aduanero', 8, 7, '1', 'Vespertino', 'DEREADUALD'),
('Mecanismos alternativos de solución de controversias', 8, 7, '1', 'Vespertino', 'MECACONTLD'),
('Derecho Fiscal II', 8, 8, '1', 'Vespertino', 'DEREFISCIILD'),
('Práctica del Derecho Administrativo', 8, 8, '1', 'Vespertino', 'PRACADMILD'),
('Práctica del Derecho Civil y Mercantil', 8, 8, '1', 'Vespertino', 'PRACMERCLD'),
('Derecho procesal constitucional', 8, 8, '1', 'Vespertino', 'DERECONSLD'),
('Derecho procesal del trabajo', 8, 8, '1', 'Vespertino', 'DEREPROCLD2'),
('Derecho de la Seguridad Social', 8, 8, '1', 'Vespertino', 'DERESEGULD'),
('Derecho Notarial y Registral', 8, 8, '1', 'Vespertino', 'DEREREGILD'),
('Práctica de Derecho Fiscal', 8, 9, '1', 'Vespertino', 'PRACDERELD2'),
('Técnicas avanzadas de litigación', 8, 9, '1', 'Vespertino', 'TECNLITILD'),
('Derecho Electoral', 8, 9, '1', 'Vespertino', 'DEREELECLD'),
('Filosofía del Derecho', 8, 9, '1', 'Vespertino', 'FILODERELD'),
('Medicina Forense', 8, 9, '1', 'Vespertino', 'MEDIFORELD'),
('Ética profesional', 8, 9, '1', 'Vespertino', 'ETICPROFLD'),
('Seminario de Investigación', 8, 9, '1', 'Vespertino', 'SEMIINVELD'),
('Historia del Arte I', 10, 1, '1', 'Matutino', 'HISTARTEILDG'),
('Teoría del Diseño I', 10, 1, '1', 'Matutino', 'TEORDISEILDG'),
('Técnicas de Redacción I', 10, 1, '1', 'Matutino', 'TECNREDAILDG'),
('Dibujo I', 10, 1, '1', 'Matutino', 'DIBUILDG'),
('Creatividad', 10, 1, '1', 'Matutino', 'CREALDG'),
('Teoría del Color', 10, 1, '1', 'Matutino', 'TEORCOLOLDG'),
('Técnicas de Investigación', 10, 1, '1', 'Matutino', 'TECNINVELDG'),
('Historia del Arte II', 10, 2, '1', 'Matutino', 'HISTARTEIILDG'),
('Teoría del Diseño II', 10, 2, '1', 'Matutino', 'TEORDISEIILDG'),
('Técnicas de Redacción II', 10, 2, '1', 'Matutino', 'TECNREDAIILDG'),
('Dibujo II', 10, 2, '1', 'Matutino', 'DIBUIILDG'),
('Estética', 10, 2, '1', 'Matutino', 'ESTELDG'),
('Comunicación I', 10, 2, '1', 'Matutino', 'COMUILDG'),
('Taller de Diseño I', 10, 2, '1', 'Matutino', 'TALLDISEILDG'),
('Psicología del Diseño I', 10, 3, '1', 'Matutino', 'PSICDISEILDG'),
('Comunicación II', 10, 3, '1', 'Matutino', 'COMUIILDG'),
('Dibujo III', 10, 3, '1', 'Matutino', 'DIBUIIILDG'),
('Taller de Diseño II', 10, 3, '1', 'Matutino', 'TALLDISEIILDG'),
('Filosofía del Arte', 10, 3, '1', 'Matutino', 'FILOARTELDG'),
('Introducción a la Informática', 10, 3, '1', 'Matutino', 'INTRINFOLDG'),
('Fotografía', 10, 3, '1', 'Matutino', 'FOTOLDG'),
('Psicología del Diseño II', 10, 4, '1', 'Matutino', 'PSICDISEIILDG'),
('Comunicación III', 10, 4, '1', 'Matutino', 'COMUIIILDG'),
('Técnicas de Ilustración I', 10, 4, '1', 'Matutino', 'TECNILUSILDG'),
('Fotografía Publicitaria', 10, 4, '1', 'Matutino', 'FOTOPUBLLDG'),
('Taller de Diseño III', 10, 4, '1', 'Matutino', 'TALLDISEIIILDG'),
('Dibujo IV', 10, 4, '1', 'Matutino', 'DIBUIVLDG'),
('Informática Aplicada al Diseño I', 10, 4, '1', 'Matutino', 'INFOAPLIILDG'),
('Historia del Arte en México I', 10, 5, '1', 'Vespertino', 'HISTMEXIILDG'),
('Semiótica de la Imagen I', 10, 5, '1', 'Vespertino', 'SEMIIMAGILDG'),
('Mercadotecnia', 10, 5, '1', 'Vespertino', 'MERCLDG'),
('Técnicas de Ilustración II', 10, 5, '1', 'Vespertino', 'TECNILUSIILDG'),
('Informática Aplicada al Diseño II', 10, 5, '1', 'Vespertino', 'INFOAPLIIILDG'),
('Serigrafía', 10, 5, '1', 'Vespertino', 'SERILDG'),
('Taller de Diseño IV', 10, 5, '1', 'Vespertino', 'TALLDISEIVLDG'),
('Historia del Arte en México II', 10, 6, '1', 'Vespertino', 'HISTMEXIIILDG'),
('Semiótica de la Imagen II', 10, 6, '1', 'Vespertino', 'SEMIIMAGIILDG'),
('Técnicas de Impresión I', 10, 6, '1', 'Vespertino', 'TECNIMPRILDG'),
('Taller de Diseño V', 10, 6, '1', 'Vespertino', 'TALLDISEVLDG'),
('Informática Aplicada al Diseño III', 10, 6, '1', 'Vespertino', 'INFOAPLIIIILDG'),
('Geometría Aplicada al Diseño Gráfico', 10, 6, '1', 'Vespertino', 'GEOMAPLILDG'),
('Estética y Narrativa en Medios Digitales', 10, 6, '1', 'Vespertino', 'ESTENARRLDG'),
('Genesa I', 10, 6, '1', 'Vespertino', 'GENEILDG'),
('Taller de Grabado', 10, 6, '1', 'Vespertino', 'TALLGRABLDG'),
('Técnicas de Ilustración III', 10, 6, '1', 'Vespertino', 'TECNILUSIIILDG'),
('Técnicas de Impresión II', 10, 7, '1', 'Vespertino', 'TECNIMPRIILDG'),
('Administración del Diseño', 10, 7, '1', 'Vespertino', 'ADMIDISELDG'),
('Taller de Diseño VI', 10, 7, '1', 'Vespertino', 'TALLDISEVILDG'),
('Publicidad', 10, 7, '1', 'Vespertino', 'PUBLLDG'),
('Diseño y Creación Multimedia', 10, 7, '1', 'Vespertino', 'DISEMULTLDG'),
('Aplicaciones Multimedia', 10, 7, '1', 'Vespertino', 'APLIMULTLDG'),
('Genesa II', 10, 7, '1', 'Vespertino', 'GENEIILDG'),
('Diseño de Exhibición', 10, 7, '1', 'Vespertino', 'DISEEXHILDG'),
('Técnicas de Ilustración IV', 10, 7, '1', 'Vespertino', 'TECNILUSIVLDG'),
('Taller de Diseño VII', 10, 8, '1', 'Vespertino', 'TALLDISEVIILDG'),
('Seminario de Investigación', 10, 8, '1', 'Vespertino', 'SEMIINVELDG'),
('Ética del Diseño', 10, 8, '1', 'Vespertino', 'ETICDISELDG'),
('Innovaciones en el Diseño Gráfico', 10, 8, '1', 'Vespertino', 'INNOGRAFLDG'),
('Seminario de Publicidad', 10, 8, '1', 'Vespertino', 'SEMIPUBLLDG'),
('Taller de Producción Digital', 10, 8, '1', 'Vespertino', 'TALLPRODLDG'),
('Legalidad Informática', 10, 8, '1', 'Vespertino', 'LEGAINFOLDG'),
('Museografía', 10, 8, '1', 'Vespertino', 'MUSELDG'),
('Diseño Textil', 10, 8, '1', 'Vespertino', 'DISETEXTLDG'),
('Medios Digitales', 10, 8, '1', 'Vespertino', 'MEDIDIGILDG'),
('ADMINISTRACION I', 1, 1, '1', 'Matutino', 'ADMIILI'),
('CONTABILIDAD I', 1, 1, '1', 'Matutino', 'CONTILI'),
('FUNDAMENTOS DE PROGRAMACION', 1, 1, '1', 'Matutino', 'FUNDPROGLI'),
('INGLES I', 1, 1, '1', 'Matutino', 'INGLILI'),
('INTRODUCCION A LA ECONOMIA', 1, 1, '1', 'Matutino', 'INTRECONLI'),
('INTRODUCCION A LAS TECNOLOGIAS COMPUTACIONALES', 1, 1, '1', 'Matutino', 'INTRCOMPLI'),
('MATEMATICAS I', 1, 1, '1', 'Matutino', 'MATEILI'),
('TALLER DE CREATIVIDAD I', 1, 1, '1', 'Matutino', 'TALLCREAILI'),
('TECNICAS DE INVESTIGACION', 1, 1, '1', 'Matutino', 'TECNINVELI'),
('ADMINISTRACION II', 1, 2, '1', 'Matutino', 'ADMIIILI'),
('CONTABILIDAD II', 1, 2, '1', 'Matutino', 'CONTIILI'),
('INGLES II', 1, 2, '1', 'Matutino', 'INGLIILI'),
('LENGUAJES DE PROGRAMACION I', 1, 2, '1', 'Matutino', 'LENGPROGILI'),
('MATEMATICAS II', 1, 2, '1', 'Matutino', 'MATEIILI'),
('MICROECONOMIA', 1, 2, '1', 'Matutino', 'MICRLI'),
('SOCIOLOGIA DE LA EMPRESA', 1, 2, '1', 'Matutino', 'SOCIEMPRLI'),
('TALLER DE CREATIVIDAD II', 1, 2, '1', 'Matutino', 'TALLCREAIILI'),
('ADMINISTRACION III', 1, 3, '1', 'Matutino', 'ADMIIIILI'),
('CONTABILIDAD III', 1, 3, '1', 'Matutino', 'CONTIIILI'),
('ESTRUCTURA DE DATOS Y ALGORITMOS', 1, 3, '1', 'Matutino', 'ESTRALGOLI'),
('INGLES III', 1, 3, '1', 'Matutino', 'INGLIIILI'),
('LENGUAJES DE PROGRAMACION II', 1, 3, '1', 'Matutino', 'LENGPROGIILI'),
('MACROECONOMIA', 1, 3, '1', 'Matutino', 'MACRLI'),
('MATEMATICAS FINANCIERAS', 1, 3, '1', 'Matutino', 'MATEFINALI'),
('TALLER DE CREATIVIDAD III', 1, 3, '1', 'Matutino', 'TALLCREAIIILI'),
('BASES DE DATOS I', 1, 4, '1', 'Matutino', 'BASEDATOILI'),
('COSTOS', 1, 4, '1', 'Matutino', 'COSTLI'),
('ESTADÍSTICA', 1, 4, '1', 'Matutino', 'ESTALI'),
('ORGANIZACIÓN COMPUTACIONAL', 1, 4, '1', 'Matutino', 'ORGACOMPLI'),
('PAQUETES CONTABLES Y ADMINISTRATIVOS', 1, 4, '1', 'Matutino', 'PAQUADMILI'),
('PSICOLOGÍA INDUSTRIAL', 1, 4, '1', 'Matutino', 'PSICINDULI'),
('SISTEMAS DE INFORMACIÓN I', 1, 4, '1', 'Matutino', 'SISTINFOILI'),
('TALLER DE CREATIVIDAD IV', 1, 4, '1', 'Matutino', 'TALLCREAIVLI'),
('ADMINISTRACIÓN FINANCIERA', 1, 5, '1', 'Vespertino', 'ADMIFINALI'),
('BASES DE DATOS II', 1, 5, '1', 'Vespertino', 'BASEDATOIILI'),
('DESARROLLO DE APLICACIONES MULTIMEDIA', 1, 5, '1', 'Vespertino', 'DESAAPLILI'),
('LIDERAZGO EMPRESARIAL', 1, 5, '1', 'Vespertino', 'LIDEEMPRLI'),
('MERCADOTECNIA', 1, 5, '1', 'Vespertino', 'MERCLI'),
('RECURSOS HUMANOS', 1, 5, '1', 'Vespertino', 'RECUHUMALI'),
('SISTEMAS DE INFORMACIÓN II', 1, 5, '1', 'Vespertino', 'SISTINFOIILI'),
('TALLER DE CREATIVIDAD V', 1, 5, '1', 'Vespertino', 'TALLCREAVLI'),
('AUDITORIA INFORMÁTICA', 1, 6, '1', 'Vespertino', 'AUDIINFOLI'),
('COMERCIO ELECTRONICO', 1, 6, '1', 'Vespertino', 'COMEELECLI'),
('DESARROLLO ORGANIZACIONAL', 1, 6, '1', 'Vespertino', 'DESAORGALI'),
('EVALUACIÓN DE PROYECTOS DE INVERSION', 1, 6, '1', 'Vespertino', 'EVALPROYLI'),
('MARCO EMPRESARIAL', 1, 6, '1', 'Vespertino', 'MARCEMPRLI'),
('SIMULACIÓN DE NEGOCIOS', 1, 6, '1', 'Vespertino', 'SIMUNEGOLI'),
('SISTEMAS DE INFORMACIÓN III', 1, 6, '1', 'Vespertino', 'SISTINFOIIILI'),
('SISTEMAS OPERATIVOS', 1, 6, '1', 'Vespertino', 'SISTOPERLI'),
('TALLER DE CREATIVIDAD VI', 1, 6, '1', 'Vespertino', 'TALLCREAVILI'),
('ADMINISTRACIÓN DE CENTROS DE COMPUTO', 1, 7, '1', 'Vespertino', 'ADMICENTLI'),
('DECISIONES GERENCIALES', 1, 7, '1', 'Vespertino', 'DECIGERELI'),
('DESARROLLO DE APLICACIONES PARA INTERNET', 1, 7, '1', 'Vespertino', 'DESAAPLILI2'),
('INGENIERÍA DE SOFTWARE I', 1, 7, '1', 'Vespertino', 'INGESOFTILI'),
('INTEGRACIÓN DE SOLUCIONES TECNOLOGICAS EN LAS ORGANIZACIONES', 1, 7, '1', 'Vespertino', 'INTEORGALI'),
('POLÍTICA Y LEGISLACIÓN INFORMÁTICA', 1, 7, '1', 'Vespertino', 'POLILEGILI'),
('REDES', 1, 7, '1', 'Vespertino', 'REDELI'),
('TALLER DE CREATIVIDAD VII', 1, 7, '1', 'Vespertino', 'TALLCREAVIILI'),
('ADMINISTRACIÓN DE LA CALIDAD', 1, 8, '1', 'Vespertino', 'ADMICALILI'),
('ADMINISTRACIÓN DE REDES', 1, 8, '1', 'Vespertino', 'ADMIREDELI'),
('CAMBIO TECNOLÓGICO EN LAS ORGANIZACIONES', 1, 8, '1', 'Vespertino', 'CAMBORGALI'),
('DIRECCIÓN ESTRATEGICA', 1, 8, '1', 'Vespertino', 'DIREESTRLI'),
('ÉTICA PROFESIONAL', 1, 8, '1', 'Vespertino', 'ETICPROFLI'),
('INGENIERÍA DE SOFTWARE II', 1, 8, '1', 'Vespertino', 'INGESOFTIILI'),
('SEMINARIO DE INVESTIGACIÓN', 1, 8, '1', 'Vespertino', 'SEMIINVELI'),
('TALLER DE CREATIVIDAD VIII', 1, 8, '1', 'Vespertino', 'TALLCREAVIIILI'),
('Teorías y Sistemas en Psicología', 4, 1, '1', 'Matutino', 'TEORPSICLP'),
('Bases Biológicas de la Conducta', 4, 1, '1', 'Matutino', 'BASEBIOLLP'),
('Introducción a la Psicología', 4, 1, '1', 'Matutino', 'INTRPSICLP'),
('Anatomía del Sistema Nervioso', 4, 1, '1', 'Matutino', 'ANATNERVLP'),
('Comunicación Oral y Escrita', 4, 1, '1', 'Matutino', 'COMUESCRLP'),
('Lógica Simbólica', 4, 1, '1', 'Matutino', 'LOGISIMBLP'),
('Informática', 4, 1, '1', 'Matutino', 'INFOLP'),
('Fundamentos Filosóficos de la Psicología', 4, 1, '1', 'Matutino', 'FUNDFILOLP'),
('Psicología Diferencial', 4, 2, '1', 'Matutino', 'PSICDIFELP'),
('Sensopercepción', 4, 2, '1', 'Matutino', 'SENSLP'),
('Desarrollo Psicológico en la Infancia', 4, 2, '1', 'Matutino', 'DESAPSICLP'),
('Neuropsicología', 4, 2, '1', 'Matutino', 'NEURLP'),
('Motivación y Emoción', 4, 2, '1', 'Matutino', 'MOTIEMOCLP'),
('Derechos Humanos y Acceso a la Salud Mental', 4, 2, '1', 'Matutino', 'DEREHUMALP'),
('Estadística I', 4, 2, '1', 'Matutino', 'ESTAILP'),
('Metodología de la Investigación en Psicología I', 4, 2, '1', 'Matutino', 'METOINVEILP'),
('Teorías de la Personalidad I', 4, 3, '1', 'Matutino', 'TEORPERSILP'),
('Aprendizaje y Memoria', 4, 3, '1', 'Matutino', 'APREMEMOLP'),
('Desarrollo Psicológico en la Adolescencia', 4, 3, '1', 'Matutino', 'DESAADOLLP'),
('Psicofisiología', 4, 3, '1', 'Matutino', 'PSICLP'),
('Psicología Social', 4, 3, '1', 'Matutino', 'PSICSOCILP'),
('Software para el Análisis de Datos', 4, 3, '1', 'Matutino', 'SOFTANALLP'),
('Estadística II', 4, 3, '1', 'Matutino', 'ESTAIILP'),
('Metodología de la Investigación en Psicología II', 4, 3, '1', 'Matutino', 'METOINVEIILP'),
('Teorías de la Personalidad II', 4, 4, '1', 'Matutino', 'TEORPERSIILP'),
('Pensamiento y Lenguaje', 4, 4, '1', 'Matutino', 'PENSLENGLP'),
('Desarrollo Psicológico de la Adultez', 4, 4, '1', 'Matutino', 'DESAPSICLP2'),
('Instrumentos de Medición en Psicología', 4, 4, '1', 'Matutino', 'INSTPSICLP'),
('Psicología Social Avanzada', 4, 4, '1', 'Matutino', 'PSICAVANLP'),
('Psicodinámica de Grupos', 4, 4, '1', 'Matutino', 'PSICGRUPLP'),
('Psicopatología I', 4, 4, '1', 'Matutino', 'PSICILP'),
('Metodología de la Investigación en Psicología III', 4, 4, '1', 'Matutino', 'METOINVEIIILP'),
('Psicología Educativa', 4, 5, '1', 'Vespertino', 'PSICEDUCLP'),
('Psicología Organizacional', 4, 5, '1', 'Vespertino', 'PSICORGALP'),
('Psicometría', 4, 5, '1', 'Vespertino', 'PSICLP2'),
('Teoría y Técnica de la Entrevista', 4, 5, '1', 'Vespertino', 'TEORENTRLP'),
('Psicología, Sexualidad y Género', 4, 5, '1', 'Vespertino', 'PSICSEXULP'),
('Psicología Clínica', 4, 5, '1', 'Vespertino', 'PSICCLINLP'),
('Psicopatología II', 4, 5, '1', 'Vespertino', 'PSICIILP'),
('Sistemas en Educación Especial', 4, 6, '1', 'Vespertino', 'SISTEDUCLP'),
('Gestión de Recursos Humanos', 4, 6, '1', 'Vespertino', 'GESTRECULP'),
('Comportamiento Organizacional', 4, 6, '1', 'Vespertino', 'COMPORGALP'),
('Evaluación de la Personalidad', 4, 6, '1', 'Vespertino', 'EVALPERSLP'),
('Psicología Comunitaria', 4, 6, '1', 'Vespertino', 'PSICCOMULP'),
('Modelos de Intervención Sistémico', 4, 6, '1', 'Vespertino', 'MODEINTELP'),
('Psicología de la Salud', 4, 6, '1', 'Vespertino', 'PSICSALULP'),
('Evaluación Psicopedagógica', 4, 7, '1', 'Vespertino', 'EVALPSICLP'),
('Mediación y Solución de Conflictos Organizacionales', 4, 7, '1', 'Vespertino', 'MEDIORGALP'),
('Reclutamiento y Selección de Talento Humano', 4, 7, '1', 'Vespertino', 'RECLSELELP'),
('Instrumentos de Evaluación Organizacional', 4, 7, '1', 'Vespertino', 'INSTORGALP'),
('Contención Emocional e Intervención en Crisis', 4, 7, '1', 'Vespertino', 'CONTINTELP'),
('Modelos de Intervención Humanistas', 4, 7, '1', 'Vespertino', 'MODEINTELP2'),
('Psicofarmacología', 4, 7, '1', 'Vespertino', 'PSICLP3'),
('Intervención Psicoeducativa', 4, 8, '1', 'Vespertino', 'INTEPSICLP'),
('Desarrollo del Talento Humano', 4, 8, '1', 'Vespertino', 'DESATALELP'),
('Integración de Estudios Psicológicos', 4, 8, '1', 'Vespertino', 'INTEPSICLP2'),
('Código Ético del Psicólogo', 4, 8, '1', 'Vespertino', 'CODIPSICLP'),
('Técnicas de Modificación Conductual', 4, 8, '1', 'Vespertino', 'TECNMODILP'),
('Modelos de Intervención Cognitivo Conductual', 4, 8, '1', 'Vespertino', 'MODEINTELP3'),
('Seminario de Investigación', 4, 8, '1', 'Vespertino', 'SEMIINVELP'),
('Introducción a la Pedagogía', 6, 1, '1', 'Matutino', 'INTRPEDALPE'),
('Sociología de la Educación', 6, 1, '1', 'Matutino', 'SOCIEDUCLPE'),
('Técnicas de Investigación', 6, 1, '1', 'Matutino', 'TECNINVELPE'),
('Psicología Evolutiva I', 6, 1, '1', 'Matutino', 'PSICEVOLILPE'),
('Historia General de la Educación', 6, 1, '1', 'Matutino', 'HISTEDUCLPE'),
('Antropología Pedagógica', 6, 1, '1', 'Matutino', 'ANTRPEDALPE'),
('Expresión Oral y Escrita', 6, 1, '1', 'Matutino', 'EXPRESCRLPE'),
('Corrientes Pedagógicas Contemporáneas', 6, 2, '1', 'Matutino', 'CORRCONTLPE'),
('Administración Educativa', 6, 2, '1', 'Matutino', 'ADMIEDUCLPE'),
('Estadística', 6, 2, '1', 'Matutino', 'ESTALPE'),
('Psicología Evolutiva II', 6, 2, '1', 'Matutino', 'PSICEVOLIILPE'),
('Desarrollo Histórico de la Educación en México', 6, 2, '1', 'Matutino', 'DESAHISTLPE'),
('Comunicación Educativa', 6, 2, '1', 'Matutino', 'COMUEDUCLPE'),
('Psicología Educativa', 6, 2, '1', 'Matutino', 'PSICEDUCLPE'),
('Teorías de la Enseñanza y el Aprendizaje', 6, 3, '1', 'Matutino', 'TEORAPRELPE'),
('Didáctica I', 6, 3, '1', 'Matutino', 'DIDAILPE'),
('Paradigmas de la Investigación Educativa I', 6, 3, '1', 'Matutino', 'PARAINVEILPE'),
('Psicotécnica Pedagógica', 6, 3, '1', 'Matutino', 'PSICPEDALPE'),
('Estructura del Sistema Educativo I', 6, 3, '1', 'Matutino', 'ESTREDUCILPE'),
('Filosofía de la Educación', 6, 3, '1', 'Matutino', 'FILOEDUCLPE'),
('Tecnología y Educación I', 6, 3, '1', 'Matutino', 'TECNEDUCILPE'),
('Evaluación Educativa', 6, 4, '1', 'Matutino', 'EVALEDUCLPE'),
('Didáctica II', 6, 4, '1', 'Matutino', 'DIDAIILPE'),
('Paradigmas de la Investigación Educativa II', 6, 4, '1', 'Matutino', 'PARAINVEIILPE'),
('Diagnóstico Pedagógico', 6, 4, '1', 'Matutino', 'DIAGPEDALPE'),
('Estructura del Sistema Educativo II', 6, 4, '1', 'Matutino', 'ESTREDUCIILPE'),
('Dinámica de Grupos', 6, 4, '1', 'Matutino', 'DINAGRUPLPE'),
('Tecnología y Educación II', 6, 4, '1', 'Matutino', 'TECNEDUCIILPE'),
('Planeación Educativa', 6, 5, '1', 'Vespertino', 'PLANEDUCLPE'),
('Andragogía', 6, 5, '1', 'Vespertino', 'ANDRLPE'),
('Teoría Curricular', 6, 5, '1', 'Vespertino', 'TEORCURRLPE'),
('Educación Especial', 6, 5, '1', 'Vespertino', 'EDUCESPELPE'),
('Estructura del Sistema Educativo III', 6, 5, '1', 'Vespertino', 'ESTREDUCIIILPE'),
('Legislación Educativa', 6, 5, '1', 'Vespertino', 'LEGIEDUCLPE'),
('Tecnologías del aprendizaje y el conocimiento I', 6, 5, '1', 'Vespertino', 'TECNCONOILPE'),
('Pedagogía laboral', 6, 6, '1', 'Vespertino', 'PEDALABOLPE'),
('Desarrollo de Habilidades para la docencia', 6, 6, '1', 'Vespertino', 'DESAHABILPE'),
('Evaluación Curricular', 6, 6, '1', 'Vespertino', 'EVALCURRLPE'),
('Pedagogía Familiar', 6, 6, '1', 'Vespertino', 'PEDAFAMILPE'),
('Organización Educativa', 6, 6, '1', 'Vespertino', 'ORGAEDUCLPE'),
('Educación Intercultural', 6, 6, '1', 'Vespertino', 'EDUCINTELPE'),
('Tecnologías del aprendizaje y el conocimiento II', 6, 6, '1', 'Vespertino', 'TECNCONOIILPE'),
('Diseño Curricular', 6, 7, '1', 'Vespertino', 'DISECURRLPE'),
('Modalidades Educativas', 6, 7, '1', 'Vespertino', 'MODAEDUCLPE'),
('Orientación Educativa I', 6, 7, '1', 'Vespertino', 'ORIEEDUCILPE'),
('Desarrollo de la Comunidad', 6, 7, '1', 'Vespertino', 'DESACOMULPE'),
('Gestión Educativa', 6, 7, '1', 'Vespertino', 'GESTEDUCLPE'),
('Desarrollo de Programas de Capacitación I', 6, 7, '1', 'Vespertino', 'DESACAPAILPE'),
('Evaluación Institucional', 6, 7, '1', 'Vespertino', 'EVALINSTLPE'),
('Taller de Diseño Curricular', 6, 8, '1', 'Vespertino', 'TALLCURRLPE'),
('Intervención Pedagógica', 6, 8, '1', 'Vespertino', 'INTEPEDALPE'),
('Seminario de Investigación', 6, 8, '1', 'Vespertino', 'SEMIINVELPE'),
('Orientación Educativa II', 6, 8, '1', 'Vespertino', 'ORIEEDUCIILPE'),
('Estrategias de Gestión Directiva', 6, 8, '1', 'Vespertino', 'ESTRDIRELPE'),
('Desarrollo de Programas de Capacitación II', 6, 8, '1', 'Vespertino', 'DESACAPAIILPE');

-- Insertando Alumnos (30 alumnos como muestra robusta)
INSERT INTO Alumnos (apellidopat, apellidomat, nombre, calle, colonia, telefono, correo, tutorapellidopat, tutorapellidomat, tutornombre, tutortelefono, tutortelefonoa, tutorcorreo, semestre, nocontrol, clave, idlicenciaturas, sexo, tipo, curp) VALUES
('Perez', 'Garcia', 'Juan', 'Av. Siempre Viva 123', 'Centro', '5551234567', 'oaxaljuanpe@lameso.edu.mx', 'Perez', 'Lopez', 'Carlos', '5559876543', '5550001111', 'carlos.perez@email.com', 1, '12345678', '123456', 1, 'M', 'Regular', 'PEGJ050101HDFR01'),
('Lopez', 'Hernandez', 'Maria', 'Calle Luna 45', 'San Rafael', '5552345678', 'oaxalmarialo@lameso.edu.mx', 'Lopez', 'Martinez', 'Jose', '5558765432', '5551112222', 'jose.lopez@email.com', 2, '23100028', '123456', 1, 'F', 'Regular', 'LOHM040202MDFR02'),
('Gomez', 'Martinez', 'Pedro', 'Blvd Sol 67', 'Juarez', '5553456789', 'oaxalpedrogo@lameso.edu.mx', 'Gomez', 'Perez', 'Luis', '5557654321', '5552223333', 'luis.gomez@email.com', 3, '2310003', '123456', 2, 'M', 'Regular', 'GOMP030303HDFR03'),
('Hernandez', 'Gonzalez', 'Ana', 'Av. Estrellas 89', 'Roma', '5554567890', 'oaxalanahe@lameso.edu.mx', 'Hernandez', 'Garcia', 'Miguel', '5556543210', '5553334444', 'miguel.hernandez@email.com', 4, '231000400', '123456', 3, 'F', 'Irregular', 'HEGA020404MDFR04'),
('Martinez', 'Lopez', 'Luis', 'Calle Nubes 12', 'Condesa', '5555678901', 'oaxalluisma@lameso.edu.mx', 'Martinez', 'Hernandez', 'Roberto', '5555432109', '5554445555', 'roberto.martinez@email.com', 5, '2310005', '123456', 4, 'M', 'Regular', 'MALL010505HDFR05'),
('Gonzalez', 'Perez', 'Laura', 'Av. Bosque 34', 'Polanco', '5556789012', 'oaxallaurago@lameso.edu.mx', 'Gonzalez', 'Gomez', 'Fernando', '5554321098', '5555556666', 'fernando.gonzalez@email.com', 6, '23100068', '123456', 5, 'F', 'Regular', 'GOPL000606MDFR06'),
('Rodriguez', 'Gomez', 'Carlos', 'Calle Rio 56', 'Del Valle', '5557890123', 'oaxalcarlosro@lameso.edu.mx', 'Rodriguez', 'Martinez', 'Eduardo', '5553210987', '5556667777', 'eduardo.rodriguez@email.com', 7, '2310007', '123456', 6, 'M', 'Regular', 'ROGC990707HDFR07'),
('Sanchez', 'Hernandez', 'Sofia', 'Blvd Mar 78', 'Coyoacan', '5558901234', 'oaxalsofiasa@lameso.edu.mx', 'Sanchez', 'Lopez', 'Ricardo', '5552109876', '5557778888', 'ricardo.sanchez@email.com', 8, '2310008', '123456', 7, 'F', 'Irregular', 'SAHS980808MDFR08'),
('Ramirez', 'Martinez', 'Jorge', 'Av. Montana 90', 'Tlalpan', '5559012345', 'oaxaljorgera@lameso.edu.mx', 'Ramirez', 'Gonzalez', 'Javier', '5551098765', '5558889999', 'javier.ramirez@email.com', 9, '2310009', '123456', 8, 'M', 'Regular', 'RAMJ970909HDFR09'),
('Cruz', 'Gonzalez', 'Daniela', 'Calle Valle 123', 'Xochimilco', '5550123456', 'oaxaldanielacr@lameso.edu.mx', 'Cruz', 'Rodriguez', 'Alejandro', '5550987654', '5559990000', 'alejandro.cruz@email.com', 1, '2310010', '123456', 9, 'F', 'Regular', 'CRGD961010MDFR10'),
('Flores', 'Rodriguez', 'Diego', 'Av. Flores 45', 'Iztapalapa', '5551234568', 'oaxaldiegofl@lameso.edu.mx', 'Flores', 'Sanchez', 'Daniel', '5559876544', '5550001112', 'daniel.flores@email.com', 2, '2310011', '123456', 10, 'M', 'Regular', 'FLRD951111HDFR11'),
('Gomez', 'Sanchez', 'Valeria', 'Calle Arbol 67', 'Gustavo A. Madero', '5552345679', 'oaxalvaleriago@lameso.edu.mx', 'Gomez', 'Ramirez', 'Andres', '5558765433', '5551112223', 'andres.gomez@email.com', 3, '2310012', '123456', 1, 'F', 'Irregular', 'GOSV941212MDFR12'),
('Hernandez', 'Ramirez', 'Miguel', 'Blvd Sol 89', 'Venustiano Carranza', '5553456780', 'oaxalmiguelhe@lameso.edu.mx', 'Hernandez', 'Cruz', 'Gabriel', '5557654322', '5552223334', 'gabriel.hernandez@email.com', 4, '2310013', '123456', 2, 'M', 'Regular', 'HERM930101HDFR13'),
('Martinez', 'Cruz', 'Camila', 'Av. Luna 12', 'Azcapotzalco', '5554567891', 'oaxalcamilama@lameso.edu.mx', 'Martinez', 'Flores', 'David', '5556543211', '5553334445', 'david.martinez@email.com', 5, '2310014', '123456', 3, 'F', 'Regular', 'MACC920202MDFR14'),
('Gonzalez', 'Flores', 'Alejandro', 'Calle Estrella 34', 'Iztacalco', '5555678902', 'oaxalalejandrogo@lameso.edu.mx', 'Gonzalez', 'Gomez', 'Hugo', '5555432110', '5554445556', 'hugo.gonzalez@email.com', 6, '2310015', '123456', 4, 'M', 'Irregular', 'GOFA910303HDFR15'),
('Rodriguez', 'Gomez', 'Mariana', 'Av. Nube 56', 'Miguel Hidalgo', '5556789013', 'oaxalmarianaro@lameso.edu.mx', 'Rodriguez', 'Hernandez', 'Victor', '5554321099', '5555556667', 'victor.rodriguez@email.com', 7, '2310016', '123456', 5, 'F', 'Regular', 'ROGM900404MDFR16'),
('Sanchez', 'Hernandez', 'Emiliano', 'Calle Bosque 78', 'Alvaro Obregon', '5557890124', 'oaxalemilianosa@lameso.edu.mx', 'Sanchez', 'Martinez', 'Manuel', '5553210988', '5556667778', 'manuel.sanchez@email.com', 8, '2310017', '123456', 6, 'M', 'Regular', 'SAHE890505HDFR17'),
('Ramirez', 'Martinez', 'Renata', 'Blvd Rio 90', 'Cuajimalpa', '5558901235', 'oaxalrenatara@lameso.edu.mx', 'Ramirez', 'Gonzalez', 'Arturo', '5552109877', '5557778889', 'arturo.ramirez@email.com', 9, '2310018', '123456', 7, 'F', 'Irregular', 'RAMR880606MDFR18'),
('Cruz', 'Gonzalez', 'Sebastian', 'Av. Mar 123', 'Magdalena Contreras', '5559012346', 'oaxalsebastiancr@lameso.edu.mx', 'Cruz', 'Rodriguez', 'Oscar', '5551098766', '5558889990', 'oscar.cruz@email.com', 1, '2310019', '123456', 8, 'M', 'Regular', 'CRGS870707HDFR19'),
('Flores', 'Rodriguez', 'Natalia', 'Calle Montana 45', 'Milpa Alta', '5550123457', 'oaxalnataliafl@lameso.edu.mx', 'Flores', 'Sanchez', 'Hector', '5550987655', '5559990001', 'hector.flores@email.com', 2, '2310020', '123456', 9, 'F', 'Regular', 'FLRN860808MDFR20'),
('Gomez', 'Sanchez', 'Leonardo', 'Av. Valle 67', 'Tlahuac', '5551234569', 'oaxalleonardogo@lameso.edu.mx', 'Gomez', 'Ramirez', 'Raul', '5559876545', '5550001113', 'raul.gomez@email.com', 3, '2310021', '123456', 10, 'M', 'Irregular', 'GOSL850909HDFR21'),
('Hernandez', 'Ramirez', 'Valentina', 'Blvd Flores 89', 'Centro', '5552345680', 'oaxalvalentinahe@lameso.edu.mx', 'Hernandez', 'Cruz', 'Armando', '5558765434', '5551112224', 'armando.hernandez@email.com', 4, '2310022', '123456', 1, 'F', 'Regular', 'HERV841010MDFR22'),
('Martinez', 'Cruz', 'Mateo', 'Calle Arbol 12', 'San Rafael', '5553456781', 'oaxalmateoma@lameso.edu.mx', 'Martinez', 'Flores', 'Guillermo', '5557654323', '5552223335', 'guillermo.martinez@email.com', 5, '2310023', '123456', 2, 'M', 'Regular', 'MACM831111HDFR23'),
('Gonzalez', 'Flores', 'Isabella', 'Av. Sol 34', 'Juarez', '5554567892', 'oaxalisabellago@lameso.edu.mx', 'Gonzalez', 'Gomez', 'Ruben', '5556543212', '5553334446', 'ruben.gonzalez@email.com', 6, '2310024', '123456', 3, 'F', 'Irregular', 'GOFI821212MDFR24'),
('Rodriguez', 'Gomez', 'Matias', 'Calle Luna 56', 'Roma', '5555678903', 'oaxalmatiasro@lameso.edu.mx', 'Rodriguez', 'Hernandez', 'Gerardo', '5555432111', '5554445557', 'gerardo.rodriguez@email.com', 7, '2310025', '123456', 4, 'M', 'Regular', 'ROGM810101HDFR25'),
('Sanchez', 'Hernandez', 'Regina', 'Blvd Estrella 78', 'Condesa', '5556789014', 'oaxalreginasa@lameso.edu.mx', 'Sanchez', 'Martinez', 'Alberto', '5554321100', '5555556668', 'alberto.sanchez@email.com', 8, '2310026', '123456', 5, 'F', 'Regular', 'SAHR800202MDFR26'),
('Ramirez', 'Martinez', 'Nicolas', 'Av. Nube 90', 'Polanco', '5557890125', 'oaxalnicolasra@lameso.edu.mx', 'Ramirez', 'Gonzalez', 'Mauricio', '5553210989', '5556667779', 'mauricio.ramirez@email.com', 9, '2310027', '123456', 6, 'M', 'Irregular', 'RAMN790303HDFR27'),
('Cruz', 'Gonzalez', 'Ximena', 'Calle Bosque 123', 'Del Valle', '5558901236', 'oaxalximenacr@lameso.edu.mx', 'Cruz', 'Rodriguez', 'Pablo', '5552109878', '5557778890', 'pablo.cruz@email.com', 1, '2310028', '123456', 7, 'F', 'Regular', 'CRGX780404MDFR28'),
('Flores', 'Rodriguez', 'Gabriel', 'Av. Rio 45', 'Coyoacan', '5559012347', 'oaxalgabrielfl@lameso.edu.mx', 'Flores', 'Sanchez', 'Julio', '5551098767', '5558889991', 'julio.flores@email.com', 2, '2310029', '123456', 8, 'M', 'Regular', 'FLRG770505HDFR29'),
('Gomez', 'Sanchez', 'Samantha', 'Calle Mar 67', 'Tlalpan', '5550123458', 'oaxalsamanthago@lameso.edu.mx', 'Gomez', 'Ramirez', 'Sergio', '5550987656', '5559990002', 'sergio.gomez@email.com', 3, '2310030', '123456', 9, 'F', 'Regular', 'GOSS760606MDFR30');

